import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import NavBar from './components/NavBar';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { ToastContainer } from 'react-toastify';

config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className}`}
      >
        <header className="sticky top-0 z-50 shadow-md bg-base-200">
          <NavBar />
        </header>
        <main className='h-[calc(100vh-64px)] lg:h-[calc(100vh-76px)]'>{children}</main>
        <ToastContainer position='bottom-right' theme='dark' />
      </body>
    </html>
  );
}
